#' An example weights column for a data set of 80 cases
#' 
#' @format A data frame with 80 rows and 1 variable
#' \describe{\item{weights_column}{data weights}
#' }
#' 
#' @source Example data generated by author
"testweights"
